"""Add single_assignment to ClinicalInstructor

Revision ID: 3ced2ddd68de
Revises: b97e535acfac
Create Date: 2024-07-22 23:26:45.152202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ced2ddd68de'
down_revision = 'b97e535acfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_instructor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('single_assignment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_instructor', schema=None) as batch_op:
        batch_op.drop_column('single_assignment')

    # ### end Alembic commands ###
