"""Add max_students_per_day to ClinicalInstructor

Revision ID: 37da31ccff46
Revises: 
Create Date: 2024-07-08 00:44:34.620664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37da31ccff46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('practice_location', sa.String(length=128), nullable=False),
    sa.Column('area_of_expertise', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('relevant_semesters', sa.String(length=128), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('available_days_to_assign', sa.String(length=128), nullable=False),
    sa.Column('max_students_per_day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('preferred_fields', sa.String(length=128), nullable=False),
    sa.Column('preferred_practice_area', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('assigned_day', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['clinical_instructor.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment')
    op.drop_table('student')
    op.drop_table('clinical_instructor')
    # ### end Alembic commands ###
