"""Initial migration

Revision ID: 87e9265739c4
Revises: 
Create Date: 2024-07-12 15:40:56.917686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e9265739c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clinical_instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('practice_location', sa.String(length=100), nullable=False),
    sa.Column('area_of_expertise_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('relevant_semesters', sa.String(length=100), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('available_days_to_assign', sa.String(length=100), nullable=False),
    sa.Column('max_students_per_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_of_expertise_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('preferred_field_id_1', sa.Integer(), nullable=False),
    sa.Column('preferred_field_id_2', sa.Integer(), nullable=False),
    sa.Column('preferred_field_id_3', sa.Integer(), nullable=False),
    sa.Column('preferred_practice_area', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['preferred_field_id_1'], ['field.id'], ),
    sa.ForeignKeyConstraint(['preferred_field_id_2'], ['field.id'], ),
    sa.ForeignKeyConstraint(['preferred_field_id_3'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('assigned_day', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['clinical_instructor.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment')
    op.drop_table('student')
    op.drop_table('clinical_instructor')
    op.drop_table('field')
    # ### end Alembic commands ###
