"""Add ArchivedSnapshot and ArchivedAssignment

Revision ID: 88fa6f4ed41c
Revises: 5116f52de221
Create Date: 2025-01-03 23:30:26.796172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fa6f4ed41c'
down_revision = '5116f52de221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archived_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('assigned_day', sa.String(length=20), nullable=False),
    sa.Column('year_semester', sa.String(length=10), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('student_email', sa.String(length=100), nullable=False),
    sa.Column('preferred_practice_area', sa.String(length=100), nullable=True),
    sa.Column('instructor_name', sa.String(length=100), nullable=False),
    sa.Column('instructor_practice_location', sa.String(length=100), nullable=False),
    sa.Column('instructor_field_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['archived_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archived_assignment')
    op.drop_table('archived_snapshot')
    # ### end Alembic commands ###
