"""Remove year_semester field from Student

Revision ID: 9224674ced4b
Revises: 88fa6f4ed41c
Create Date: 2025-01-04 19:14:33.387334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9224674ced4b'
down_revision = '88fa6f4ed41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_assignment', schema=None) as batch_op:
        batch_op.drop_column('year_semester')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_semester', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
